# Generated by Django 4.2.1 on 2024-07-03 11:35

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=70)),
                ('name_ru', models.CharField(max_length=70, null=True)),
                ('name_uz', models.CharField(max_length=70, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='FreeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('count', models.PositiveIntegerField()),
                ('free_count', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
