# Generated by Django 4.2.1 on 2024-06-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
