# Generated by Django 4.2.1 on 2024-06-29 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_galleryphoto_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FreeProduct',
        ),
    ]
