# Generated by Django 4.2.1 on 2024-07-01 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('order', '0002_initial'),
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('user', '0002_usercontactapplication'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Profile',
            new_name='User',
        ),
        migrations.AlterField(
            model_name='usercontactapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
