# Generated by Django 4.2.1 on 2024-06-28 13:02

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('count', models.PositiveIntegerField(verbose_name='count')),
                ('free_count', models.PositiveIntegerField(verbose_name='')),
                ('latitude', models.FloatField(max_length=100)),
                ('longtitude', models.FloatField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_changed_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('WA', 'Waiting'), ('PR', 'Process'), ('CD', 'Completed')], default='WA', max_length=2)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
