# Generated by Django 4.2.1 on 2024-07-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
